### ISSUE TITLE
About

### ISSUE THREAD

**Issue by jueyang** [cunyjschool/newsplay#5]
- About
  - Why to use this?
  - How does this work?
  - Who build this?
  - Contact info

**Comment by jeremycaplan** [comment]
NewsPlay is a simple game to practice generating creative approaches to covering news stories. 

Here's how to Play: 
1. Load the page at cunyjschool.github.io/newsplay/ to see a randomly-selected news story title and brief summary, drawn from a recent NY Times story. 
2. Look at the constraints on the right side of the page for a suggested story type, a supplemental media type, a deadline, a supplemental platform and optionally, an audience age group. 
3. For the next 5 minutes, develop an approach to that story that you could pitch to a publication editor for a publication of your choice. 
4. In addition to drafting a three to five-sentence story pitch for a story following up on the given news story, use the supplemental media type and platform to inspire you to propose supplemental approaches for additional social media content.
5. Submit the approach you come up with through the button on the main cunyjschool.github.io/newsplay/ page. 
Reload the page and give the next story a shot!  

*_Who Built This? *_ NewsPlay was designed by Jeremy Caplan and developed and coded by Jue Yang. We'd love your suggestions for ways to improve the game. 

Contact Info: To share ideas, email jeremy.caplan@journalism.cuny.edu

**Comment by jueyang** [comment]
A few thoughts:
- The step-by-step instructions can be included in the "?" button (which has different text now, but is easy to change).
- For the about page, I think a more succinct version would work better. I've edited the text below.
- I created the current site layout/visual to be playful because we are pitching this as a "game". I think the language should reflect that spirit as well.

### NewsPlay is a game to generate creative approaches to covering news stories. It's like Iron Chef, but for news. Can you cook the news ingredients with a creative method?

### Ingredients

A summary of a recent article story from the NY Times (with a link to the original story)

### Method Options

A collection of new constraints to present the story including: a suggested story type, a supplemental media type, a deadline, a supplemental platform and optionally, an audience age group

### How to

On loading the site, you will be given the ingredients and the options. Use the next 5 minutes to develop an approach to that story that you could pitch to a publication editor for a publication of your choice.

Draft a 3- to 5-sentence pitch. If you feel inspired by the supplemental media type or the platform, add your ideas for additional social media content in your pitch.

### Credits

Game Design: Jeremy Caplan
UI/Visual Design/Code: Jue Yang
CUNY Graduate School of Journalism

### Contact us

We'd love your suggestions for ways to improve the game. To share ideas, email jeremy.caplan@journalism.cuny.edu

**Comment by jeremycaplan** [comment]
Looks good, Jue. I like your idea of making it more playful. Smart edits. 

At the end, right before the Credits line, let's note that we invite people to share the story approach they generate with others (and see others' ideas) via the form linked on the page.

**Comment by jueyang** [comment]
Added!
